model:
  num_epochs: 10
  num_samples: 128
  num_layers: 4
  hidden_dim: 128  # Default for GPU
  device: auto  # Automatically select GPU if available, else CPU
  cpu_hidden_dim: 32  # Hidden dimension if running on CPU
  charnum_service: 15 # Number of services per instance
  charnum_s: 5 # Number of services components characteristics
  charnum_n: 4 # Number of computing nodes characteristics
  charnum_se: 1 # Number of services edge characteristics
  charnum_ne: 2 # Number of computing nodes edge characteristics
  charnum_node: 20 # Number of computing nodes per instance
  charnum_component: 5 # Number of component per service per instance


 